Update dotnetcore.yml
5

diff --git a/.github/workflows/dotnetcore.yml b/.github/workflows/dotnetcore.yml
--- a/.github/workflows/dotnetcore.yml
+++ b/.github/workflows/dotnetcore.yml
@@ -15,6 +15,8 @@ jobs:
 
     - run: dotnet restore build/build.csproj
     - run: dotnet build --no-restore build/build.csproj
+    - run: dotnet publish build/build.csproj -c Release -o build/output
+
     - run: dotnet test build/build.csproj
 
     - name: Install CycloneDX CLI
@@ -27,12 +29,16 @@ jobs:
         sudo mv cyclonedx /usr/local/bin/cyclonedx
 
     - name: Verify CycloneDX CLI Installation
-      run: |
-        cyclonedx --version
+      run: cyclonedx --version
 
     - name: Generate SBOM
       run: |
-        cyclonedx convert --input-file build/build.csproj --output-file sbom.xml --input-format xml --output-format xml
+        if [ -f "build/output/build.dll" ]; then
+          cyclonedx convert --input-file build/output/build.dll --output-file sbom.xml --input-format xml --output-format xml
+        else
+          echo "Error: DLL file not found in build/output/"
+          exit 1
+        fi
 
     - name: Upload SBOM Artifact
       uses: actions/upload-artifact@v3
