Update dotnetcore.yml
test 7

diff --git a/.github/workflows/dotnetcore.yml b/.github/workflows/dotnetcore.yml
--- a/.github/workflows/dotnetcore.yml
+++ b/.github/workflows/dotnetcore.yml
@@ -4,7 +4,6 @@ on: [push]
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     steps:
@@ -28,15 +27,22 @@ jobs:
     # Download and Install CycloneDX CLI from tar.gz
     - name: Install CycloneDX CLI
       run: |
-        VERSION=0.26.0  # Update this to the valid version available on GitHub
+        VERSION=0.25.0  # Change this to a valid version found on GitHub
         DOWNLOAD_URL="https://github.com/CycloneDX/cyclonedx-cli/releases/download/v$VERSION/cyclonedx-linux-x64.tar.gz"
-        
+
         # Debug: Print the download URL
         echo "Downloading CycloneDX CLI from $DOWNLOAD_URL"
 
+        # Check if the download URL is valid
+        http_response=$(curl --write-out "%{http_code}" --silent --output /dev/null "$DOWNLOAD_URL")
+        if [ "$http_response" -ne 200 ]; then
+          echo "Error: Failed to download the file. HTTP response code: $http_response"
+          exit 1
+        fi
+
         # Download the tar.gz file
         curl -sL "$DOWNLOAD_URL" -o cyclonedx.tar.gz
-        
+
         # Debug: Check the downloaded file's type
         file cyclonedx.tar.gz
         
